In [1]:
def _MA_screen(df, x):
    df['SMA'] = round(df['Adj Close'].rolling(window=x).mean(), 2)  # Simple Moving Average

    # TEMA triple exponential moving average | EMA Exponential Moving Average
    df['EMA1'] = round(df['Adj Close'].ewm(span=x, adjust=False).mean(), 2)
    df['EMA2'] = round(df['EMA1'].ewm(span=x, adjust=False).mean(), 2)
    df['EMA3'] = round(df['EMA2'].ewm(span=x, adjust=False).mean(), 2)
    df['TEMA'] = 3 * (df['EMA1'] - df['EMA2']) + df['EMA3']

    # up/down from previous 2 days
    df['SMA_2'] = df.SMA.shift(2)
    df['TEMA_2'] = df.TEMA.shift(2)
    df['SMA_up'] = df.apply(lambda x: '+' if x['SMA'] >= x['SMA_2'] else '-', axis=1)
    df['TEMA_up'] = df.apply(lambda x: '+' if x['TEMA'] >= x['TEMA_2'] else '-', axis=1)

    # reverse up/down
    df['SMA_up_1'] = df.SMA_up.shift(1)
    df['TEMA_up_1'] = df.TEMA_up.shift(1)
    df = df.dropna(subset=['SMA', 'SMA_2', 'TEMA', 'TEMA_2', 'SMA_up_1', 'TEMA_up_1'])
    df['SMA_up_rev'] = df.apply(lambda x: x['SMA_up'] if x['SMA_up'] != x['SMA_up_1'] else '', axis=1)
    df['TEMA_up_rev'] = df.apply(lambda x: x['TEMA_up'] if x['TEMA_up'] != x['TEMA_up_1'] else '', axis=1)

    SMA_seq = ''
    TEMA_seq = ''
    seq = 0
    for i in df.index[::-1]:  # look backwards
        seq += 1
        if bool(SMA_seq) & bool(TEMA_seq):
            break
        if (not SMA_seq) & bool(df['SMA_up_rev'][i]):
            SMA_seq = df['SMA_up_rev'][i] + str(seq)
        if (not TEMA_seq) & bool(df['TEMA_up_rev'][i]):
            TEMA_seq = df['TEMA_up_rev'][i] + str(seq)
    return [TEMA_seq, SMA_seq]

In [2]:
def rsi(df, periods=14, ema=True):
    close_delta = df['Adj Close'].diff()

    # Make two series: one for lower closes and one for higher closes
    up = close_delta.clip(lower=0)
    down = -1 * close_delta.clip(upper=0)

    if ema == True:
        # Use exponential moving average
        ma_up = up.ewm(com=periods - 1, adjust=True, min_periods=periods).mean()
        ma_down = down.ewm(com=periods - 1, adjust=True, min_periods=periods).mean()
    else:
        # Use simple moving average
        ma_up = up.rolling(window=periods, adjust=False).mean()
        ma_down = down.rolling(window=periods, adjust=False).mean()

    rsi = ma_up / ma_down
    rsi = 100 - (100 / (1 + rsi))
    return round(rsi[-1])

In [3]:
import contextlib
import io

import pandas as pd
import yfinance as yf

yf.pdr_override()
pd.options.mode.chained_assignment = None  # default='warn'

def _MA_screen_list(stockList, x):
    stockList = list(set(stockList))  # make elements unique
    stockList = sorted(stockList)
    rows = []
    for symbol in stockList:
        try:
            with contextlib.redirect_stdout(io.StringIO()):
                #df_yh = yf.download(symbol, period="120d")
                #df_yh = yf.download(symbol, period="20d", interval="1h")
                df_yh = yf.download(symbol, period="5d", interval="15m")                
            row = _MA_screen(df_yh, x)
            row.append(rsi(df_yh))
            row.append(symbol)
            rows.append(row)
        except Exception:
            print(symbol)
    out_df = pd.DataFrame(rows, columns=['TEMA_seq', 'SMA_seq', 'RSI', 'symbol'])

    out_df.TEMA_seq = out_df.TEMA_seq.astype(float)
    out_df.SMA_seq = out_df.SMA_seq.astype(float)
    out_df = out_df.sort_values(by=['TEMA_seq', 'SMA_seq'], ascending=False)
    return out_df

In [4]:
# +1 buy
stockList = ['QS','NVDA','NNOX','SOXL','ABNB','TCEHY','DIDI']
_MA_screen_list(stockList, 20)

   TEMA_seq  SMA_seq  RSI symbol
1     -12.0    -12.0   17   DIDI
6     -12.0    -12.0   30  TCEHY
2     -13.0    -12.0   30   NNOX
4     -13.0    -12.0   31     QS
5     -13.0    -13.0   20   SOXL
0     -14.0    -19.0   30   ABNB
3     -14.0    -32.0   22   NVDA

In [5]:
# -1 sell
stockList = ['ASTS','SPCE','NIO','GBTC','ETHE','NUGT','BLDP','CRSP','API','COIN']
_MA_screen_list(stockList, 20)

   TEMA_seq  SMA_seq  RSI symbol
2      -4.0    -12.0   36   BLDP
8      -4.0    -12.0   37   NUGT
4     -12.0     -5.0   43   CRSP
6     -12.0    -12.0   18   GBTC
5     -12.0    -38.0   27   ETHE
9     -13.0     -9.0   34   SPCE
1     -13.0    -11.0   31   ASTS
0     -13.0    -12.0   28    API
3     -13.0    -13.0   33   COIN
7     -13.0    -13.0   21    NIO

In [ ]:
# test _MA_screen with 1 symbol
import contextlib
import io

import pandas as pd
import yfinance as yf

yf.pdr_override()
pd.options.mode.chained_assignment = None  # default='warn'

with contextlib.redirect_stdout(io.StringIO()):
    df_yh = yf.download('AMC', period="120d")
    #df_yh = yf.download('AMC', period="20d", interval="1h")
    
_MA_screen(df_yh, 20)

In [ ]:
# Scan index companies
import finnhub

finnhub_client = finnhub.Client(api_key="c3ssr9qad3ide69e8l60")  # sandbox_c3ssr9qad3ide69e8l6g
symbols = finnhub_client.indices_const(symbol='^DJI')  # ^NDX ^RUT ^GSPC ^DJI
stockList = symbols['constituents']
_MA_screen_list(stockList, 20)
# out_df[(out_df['TEMA_seq'] > 0) & (out_df['TEMA_seq'] <=3) & (out_df['SMA_seq'] <= 3)] # reverse up, sell P

In [ ]:
# Scan index companies
from pandas import DataFrame
from pytickersymbols import PyTickerSymbols

stock_data = PyTickerSymbols()
lst = stock_data.get_stocks_by_index('DOW JONES')  # DOW JONES | S&P 500 | NASDAQ 100
df = DataFrame(lst)
stockList = df['symbol'].tolist()  # get list from a column

_MA_screen_list(stockList, 20)

In [ ]:
pd.set_option('display.width', 1000)  # display all columns without wrapping
pd.set_option('display.max_columns', None)  # display all columns
pd.set_option('display.max_rows', None)  # display all rows